server:
  port: 8080

spring:
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
